// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/27/2026, 6:08:45 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/benjaminruyer/Desktop/careefinder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/benjaminruyer/Desktop/careefinder/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/benjaminruyer/Desktop/careefinder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/benjaminruyer/Desktop/careefinder/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/benjaminruyer/Desktop/careefinder/plugins/**/*.{js,ts,mjs}","/Users/benjaminruyer/Desktop/careefinder/composables/**/*.{js,ts,mjs}","/Users/benjaminruyer/Desktop/careefinder/utils/**/*.{js,ts,mjs}","/Users/benjaminruyer/Desktop/careefinder/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/benjaminruyer/Desktop/careefinder/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/benjaminruyer/Desktop/careefinder/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/benjaminruyer/Desktop/careefinder/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;